#!/bin/bash

createHotSpot()
{
	ip a add 192.168.50.5/24 brd + dev "wlan0"
	ip link set dev "wlan0" up
	dhcpcd -k "wlan0" >/dev/null 2>&1
    	iptables -t nat -A POSTROUTING -o "eth0" -j MASQUERADE
    	iptables -A FORWARD -i "eth0" -o "wlan0" -m state --state RELATED,ESTABLISHED -j ACCEPT
    	iptables -A FORWARD -i "wlan0" -o "eth0" -j ACCEPT
    	systemctl start dnsmasq
    	systemctl start hostapd
}

if !(wpa_cli -i "wlan0" status | grep 'ip_address' >/dev/null)
then
        echo "No wifi connection found"
	sudo python /home/pi/Documents/School/apvalley-1819-litup/Rgb-Matrix/rpi-rgb-led-matrix/bindings/python/samples/screensaver.py -i /home/pi/Documents/School/apvalley-1819-litup/RaspberryPi/wifi --led-gpio-mapping='adafruit-hat-pwm' --led-brightness=70
        createHotSpot
else
        echo "Wifi connection found"
	fullIp=$(wpa_cli -i "wlan0" status | grep 'ip_address')
	end=${fullIp##*.}
	ip=${fullIp/$end/100}
	line="static $ip/24"
	echo $line
	sudo sed -i -e "66s#.*#$line#" /etc/dhcpcd.conf
	sudo systemctl daemon-reload
	sudo systemctl stop dhcpcd.service
	sudo ip addr flush dev wlan0
	sudo systemctl start dhcpcd.service
	sudo systemctl restart networking.service
	sleep 1
	echo $(wpa_cli -i "wlan0" status | grep 'ip_address')
	#sudo python /home/pi/Documents/School/apvalley-1819-litup/RaspberryPi/APIcall.py
fi
